[package]
name = "second-stack"
version = "0.1.0"
authors = ["Zac <that3percent@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
testdrop = "0.1.2"

[features]
experimental = []